server:
  port: 8002

spring:
  application:
    name: auth-server

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka