server:
  port: 8001

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      default-filters:
        - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
