server:
  port: 8003

spring:
  application:
    name: order
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      connection-timeout: 30000

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka


