spring:
  application:
    name: eureka
  profiles:
    active: local
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

